### ISSUE TITLE
Multiple audio tracks overlay?

### ISSUE THREAD

**Issue by suraj813** [ShiiRochi/wavesurfer-react#16]
Thank you for making this library! 
I want to display the waveforms for multiple tracks overlaid in the same container. I see that wavesurfer.js has an option for splitChannels with overlay: true. I was wondering if I could do something like that with multiple tracks instead? Appreciate any pointers you might have!

**Comment by ShiiRochi** [comment]
From my POV, your question is better to be asked in `wavesurfer.js` repository. Because as soon as this lib is just a wrapper around it (think of it as a some kind of a syntax sugar for React) there can't be things that are not present in `wavesurfer.js` natively. At least for now, I don't (and may be _don't want to_) try to implement some custom stuff on top of `wavesurfer.js`.

I can give you the following advice on "what to do": 
if `wavesurfer.js` allows you to do it natively, then use appropriate option, otherwise try to investigate the case whether you can do it with some plugin? If you succeeded, then you can just pass this plugin inside `plugins` list and use it as all other plugins.
