### ISSUE TITLE
Example of in use

### ISSUE THREAD

**Issue by jamesryan-dev** [ShiiRochi/wavesurfer-react#57]
Not sure how to use 

Could the docs show a working example with a src value, options and even hosted on a demo site please?

**Comment by ShiiRochi** [comment]
You can click on _Codesandbox_ badge and it will open demo with it

**Comment by ShiiRochi** [comment]
@jamesryan-dev, wavesurfer-react package components do not have `src` prop. Currently, to load an audio, you have to receive `ref` of wavesurfer instance and use its API.

**Comment by ShiiRochi** [comment]
@MaxInMoon, I've searched for issues in wavesurfer.js repo, and this the first thing that I found:
https://github.com/katspaugh/wavesurfer.js/issues/54

**Comment by ShiiRochi** [comment]
@jamesryan-dev, @MaxInMoon you have to enable CORS requests for files you need to display on your webpage, otherwise store them inside public folder of your webpage. I tried to store file in file.io service, but their CORS policy does not allow me to download anything from codesandbox.io.
-----------------------------------
I will close this issue, because this issue relates to interaction between different domains more, than to the package functionality.
